name: CI
on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        stack: ["heroku-20", "heroku-22", "heroku-24"]
    runs-on: ubuntu-22.04
    env:
      STACK: ${{ matrix.stack }}
      HATCHET_APP_LIMIT: 100
      HATCHET_RETRIES: 3
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_API_USER: ${{ secrets.HEROKU_API_USER }}
      IS_RUNNING_ON_CI: 1
      HATCHET_EXPENSIVE_MODE: 1
      PARALLEL_SPLIT_TEST_PROCESSES: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Hatchet setup
        run: bundle exec hatchet ci:setup
      - name: Run test suite
        run: bundle exec parallel_split_test spec/
